# Generated by Django 4.0.3 on 2022-04-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0004_piloto_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piloto',
            old_name='tarjeta_presentacion',
            new_name='cuerpo',
        ),
    ]
