# Generated by Django 4.0.3 on 2022-04-14 16:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0005_rename_tarjeta_presentacion_piloto_cuerpo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piloto',
            name='pais',
        ),
        migrations.AddField(
            model_name='piloto',
            name='subtitulo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piloto',
            name='titulo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
