# Generated by Django 4.0.3 on 2022-04-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0009_piloto_fecha_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Circuito',
        ),
        migrations.DeleteModel(
            name='Equipos',
        ),
    ]
