# Generated by Django 4.0.3 on 2022-04-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0010_delete_circuito_delete_equipos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piloto',
            old_name='imagen',
            new_name='image',
        ),
    ]
