# Generated by Django 4.0.3 on 2022-04-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0011_rename_imagen_piloto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piloto',
            old_name='image',
            new_name='imagen',
        ),
    ]
