# Generated by Django 4.0.3 on 2022-04-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextension',
            old_name='more_description',
            new_name='mas_descripcion',
        ),
    ]
